name: JSR

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  publish:
    needs: ['tests', 'cleanliness']
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # The OIDC ID token is used for authentication with JSR.
    steps:
      - uses: actions/checkout@v4
      - name: Validate package
        run: npx jsr publish --dry-run
      - name: Publish package
        run: npx jsr publish
  tests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - windows-2022
          - macOS-14
        deno:
          - v2.6.3
          - v2.x

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}

      - name: Run tests
        run: deno task test

  cleanliness:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.6.3

      - name: Run formatter
        run: deno fmt --check

      - name: Run linter
        run: deno lint
